### ISSUE TITLE
when deleting tasks rapidly, somtimes only some of the tasks are deleted after refreshing.

### ISSUE THREAD

**Issue by yuvalNakav** [kosta1221/zen-spark#1]
when deleting tasks rapidly, somtimes only some of the tasks are deleted after refreshing.
**Step to reproduce :**
1.Add multible tasks .
2.Delete the tasks rapidly 

**Expected result :**
all tasks should be deleted.

**Actual Result:**
somtimes only some of the tasks are deleted after refreshing.

**Comment by kosta1221** [comment]
Fixed (now the buttons are unclickable when loading).
